version: "3.9"
services:
  database:
    image: "postgres:15"
    container_name: "postgres"
    ports:
      - "9452:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./script:/script

volumes:
  database-data: